Minimum Viable Product for generate Reports
FreddieMwau/OnboardingReporter pull request #4
Opened 2024-03-22 07:20 UTC by mbunix

**** Check that the Pr Creates A Ba chart and a Pie chart Regards to data tables produced by the queries 
**** Check that an email is sent to technical support for the same

2024-03-22 15:33 UTC, FreddieMwau requested changes
Get rid of the Business Exceptions Present in your workflows

2024-03-25 11:47 UTC, mbunix commented
> Get rid of the Business Exceptions Present in your workflows

Removed all of them on visualize

2024-03-27 15:29 UTC, FreddieMwau approved these changes

2024-03-27 15:30 UTC, FreddieMwau approved these changes
great work

2024-03-27 15:30 UTC, merged